### ISSUE TITLE
启动时报错Unhandled exception in script

### ISSUE THREAD

**Issue by gyy0814** [HellSakura/UpdateWeather#13]
Traceback (most recent call last):
  File "UpdateWeather.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "hid\__init__.py", line 30, in <module>
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
![image](https://github.com/HellSakura/UpdateWeather/assets/74656537/1063d21f-4255-4ca6-ba45-dbedd707eeb1)

**Comment by HellSakura** [comment]
请检查是否正确放置了「hidapi」文件

**Comment by gyy0814** [comment]
(＞人＜；)对不起
